[build]
  command = "npm run prerender"
  functions = "./functions"
  publish = "dist/angular-stripe-checkout/browser"
[dev]
  command = "npm run start"
  functions = "./functions"
  publish = "src"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
